In [15]:
import numpy as np

In [16]:
x2 = np.array([
    [1,2,3],
    [4,5,6]
])
print(x2)
print(type(x2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [17]:
a = np.arange(10,51,0.5)
print(a)
print(a.shape)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5
 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5
 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5
 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5 50.  50.5]
(82,)


In [18]:
b = np.linspace(10,20,100)
print(b)

[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.87878788 17.97979798 18.08080808 18.18181818 18

In [23]:
c = np.random.randint(10,1000000,(5,5))
print(c)


[[830068 893690 499822 773796 318701]
 [118027 346442 798780 485459  37241]
 [329721 529045  40182 749731 783507]
 [632694 211158 161944  13735 840958]
 [530276 589439 848227 372541 547359]]


In [24]:
print(a)
print('size')
print(a.size)
print('shape')
print(a.shape)
print('dimension')
print(a.ndim)
print('dtype')
print(a.dtype)


[[2 4 6]
 [1 3 5]]
size
6
shape
(2, 3)
dimension
2
dtype
int32


In [25]:
x =np.random.randint(10,99,(4,5))
print(x)
print(x.reshape(5,4))
print(x.reshape(1,20))
print(x.reshape(20,1))
print(x.reshape(2,10))
print(x.reshape(10,2))

[[28 51 58 40 54]
 [37 91 30 95 46]
 [36 60 74 57 87]
 [63 83 27 70 28]]
[[28 51 58 40]
 [54 37 91 30]
 [95 46 36 60]
 [74 57 87 63]
 [83 27 70 28]]
[[28 51 58 40 54 37 91 30 95 46 36 60 74 57 87 63 83 27 70 28]]
[[28]
 [51]
 [58]
 [40]
 [54]
 [37]
 [91]
 [30]
 [95]
 [46]
 [36]
 [60]
 [74]
 [57]
 [87]
 [63]
 [83]
 [27]
 [70]
 [28]]
[[28 51 58 40 54 37 91 30 95 46]
 [36 60 74 57 87 63 83 27 70 28]]
[[28 51]
 [58 40]
 [54 37]
 [91 30]
 [95 46]
 [36 60]
 [74 57]
 [87 63]
 [83 27]
 [70 28]]


In [26]:
print(x.flatten())

[28 51 58 40 54 37 91 30 95 46 36 60 74 57 87 63 83 27 70 28]


In [27]:
y = np.random.randint(10,99,(5,2))
print(y)

[[68 80]
 [94 73]
 [50 28]
 [78 10]
 [77 73]]


In [29]:
y.T

array([[68, 94, 50, 78, 77],
       [80, 73, 28, 10, 73]])

In [36]:
print(y)
print(y.sum())
print(y.sum(axis=0))
print(y.sum(axis=1))

print(y.max(),y.min())
print(y.argmax(),y.argmin())

[[68 80]
 [94 73]
 [50 28]
 [78 10]
 [77 73]]
631
[367 264]
[148 167  78  88 150]
94 10
2 7


In [37]:
x = np.random.randint(10,100,(10,10))
print(x)

[[39 45 25 40 72 89 82 60 83 94]
 [78 23 36 46 30 87 72 10 85 38]
 [72 26 13 60 40 31 14 12 90 63]
 [29 91 13 70 13 59 75 12 19 53]
 [51 68 62 80 20 73 97 78 58 30]
 [41 46 67 83 31 69 39 11 12 98]
 [90 85 62 35 14 72 96 27 19 83]
 [76 65 25 96 41 84 66 61 51 13]
 [82 23 98 29 18 87 64 78 12 92]
 [83 24 19 64 59 38 92 94 85 42]]


In [44]:
x[0,0]
x[-1,-1]
print(x[:,-1])
print(x[:,-3:])

[94 38 63 53 30 98 83 13 92 42]
[[60 83 94]
 [10 85 38]
 [12 90 63]
 [12 19 53]
 [78 58 30]
 [11 12 98]
 [27 19 83]
 [61 51 13]
 [78 12 92]
 [94 85 42]]


In [45]:
print(np.where(x == 66))

(array([7], dtype=int64), array([6], dtype=int64))
